# Site settings
title: System76 Support
email: cassidy@system76.com
description: > # this means to ignore newlines until "baseurl:"
  Official System76 Support and useful documentation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://support.system76.com" # the base hostname & protocol for your site

collections:
  articles:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM # Use GitHub markdown extensions
  syntax_highlighter: rouge

plugins:
  - jekyll-redirect-from
